blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://discord.gg/channels/1302834707125501992/1302834707880214572
    about: Ask questions and discuss with other community members
