name: Create Pull Request on New Branch

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do Repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Extrair o Nome da Branch
      - name: Extract Branch Name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # 4. Criar a Pull Request
      - name: Criar Pull Request Automática
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}  # Branch de origem (nova branch)
          title: "PR Automática: Merge `${{ env.BRANCH_NAME }}` para main"
          commit-message: "Automated PR for branch creation"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          signoff: false
          delete-branch: false
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/renanlido/create-pull-request
          labels: automated-pr
          assignees: renanlido  # Substitua pelo seu usuário ou pelo responsável adequado
          draft: false