name: Create Pull Request on New Branch

on:
  push:
    branches-ignore:
      - 'main'   # Ignora pushes na main para evitar loops
      - 'master' # Ignora pushes na master também, se aplicável

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para ter acesso ao histórico completo

      - name: Extract Branch Name
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use um PAT token ao invés do GITHUB_TOKEN
          base: main
          title: "feat: Merge ${{ env.BRANCH_NAME }} into main"
          body: |
            ## Automated Pull Request

            Branch: ${{ env.BRANCH_NAME }}
            Triggered by: ${{ github.actor }}

            ### Changes Included
            - Automated PR creation from branch ${{ env.BRANCH_NAME }}
            - Please review the changes before merging

          labels: |
            automated-pr
            needs-review
          assignees: ${{ github.actor }}
          draft: false