name: Create Pull Request on New Branch

on:
  create:
    ref_type: branch

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do Repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Extrair o Nome da Branch
      - name: Extract Branch Name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # 3. Verificar se a Branch é Permitida (Opcional)
      - name: Validate Branch Name
        if: startsWith(env.BRANCH_NAME, 'feature/') || startsWith(env.BRANCH_NAME, 'bugfix/') || startsWith(env.BRANCH_NAME, 'hotfix/')
        run: echo "Branch name is valid."

      # 4. Criar a Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # Branch de destino para a PR
          head: ${{ env.BRANCH_NAME }}  # Branch de origem (nova branch)
          title: "Automated PR: Merge `${{ env.BRANCH_NAME }}` into main"
          body: |
            Esta é uma PR automática para integrar as mudanças da branch `${{ env.BRANCH_NAME }}` na branch `main`.
            - Atualizado em: *${{ steps.extract_branch.outputs.BRANCH_NAME }}*
            - Auto-gerado pela GitHub Action.
          labels: automated-pr
          assignees: renanlido
          draft: false