name: Create Pull Request on New Branch

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

permissions:
  pull-requests: write
  contents: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Extract Branch Name
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Debug Branch Info
        run: |
          echo "Current branch: ${{ env.BRANCH_NAME }}"
          git branch -a
          git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: main
          head: ${{ env.BRANCH_NAME }}  # A branch que contém suas alterações
          title: "feat: ${{ env.BRANCH_NAME }} into main"
          body: |
            Automated PR from ${{ env.BRANCH_NAME }}

            Please review the changes.
          draft: false
          reviewers: renanlido
          branch: ${{ env.BRANCH_NAME }}