name: Create Pull Request on New Branch

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do Repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Extrair o Nome da Branch
      - name: Extract Branch Name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # 4. Criar a Pull Request
      - name: Criar Pull Request Automática
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ env.BRANCH_NAME }}  # Branch de origem (nova branch)
          title: "PR Automática: Merge `${{ env.BRANCH_NAME }}` para main"
          body: |
            Esta é uma PR automática para integrar as mudanças da branch `${{ env.BRANCH_NAME }}` na branch `main`.

            **Detalhes da Branch:**
            - Nome da Branch: `${{ env.BRANCH_NAME }}`
            - Criada por: @${{ github.actor }}

            *Auto-gerado pela GitHub Action.*
          labels: automated-pr
          assignees: renanlido  # Substitua pelo seu usuário ou pelo responsável adequado
          draft: false