name: Create Pull Request on New Branch

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

permissions:
  pull-requests: write
  contents: write
  actions: write
  packages: write
  repository-projects: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update Main
          title: PR Develop to Main
          branch: main
          draft: true
          reviewers: renanlido
