name: 🚀 pkg-pr-new
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"


      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish

      # //criar tag version patch pegando a tag dinamicamente e publicar no npm
      - run: git tag -a v$(npm version patch) -m "v$(npm version patch)"
      - run: git push origin v$(npm version patch)
      - run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}