name: 🚀 PR

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request]

permissions:
  actions: write
  contents: read
  pull-requests: write

jobs:
  lint:
    name: ⬣ Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js com pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Instalar dependências
        run: pnpm install

      - uses: biomejs/setup-biome@v2

      - run: biome ci . --reporter=github

  typecheck:
    name: 🔎 Type Check
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancelar Execuções Anteriores
        uses: styfle/cancel-workflow-action@0.12.1

      - uses: actions/checkout@v4

      - name: Configurar Node.js com pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Instalar dependências
        run: pnpm install

      - name: 🔎 Executar Verificação de Tipos
        run: pnpm run typecheck